# Generated by Django 5.0.3 on 2024-03-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pengguna", "0002_genre_paspor_penulis_film_orang_buku"),
    ]

    operations = [
        migrations.AddField(
            model_name="biodata",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="pengguna"),
        ),
    ]
