# Generated by Django 5.0.3 on 2024-05-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pengguna", "0003_biodata_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="biodata",
            options={"verbose_name_plural": "1. Biodata"},
        ),
    ]
